### ISSUE TITLE
Source code

### ISSUE THREAD

**Issue by BlueTree242** [Supergoed1/InfiniteBuckets#1]
Please put the source code

**Comment by Supergoed1** [comment]
Okay, but why?

**Comment by BlueTree242** [comment]
dude, so people can make PR and improve the plugin, see the code and learn, and so on

**Comment by Supergoed1** [comment]
Fair enough, I honestly didn't think anyone would care so I didn't upload source. But I'll upload it now

**Comment by BlueTree242** [comment]
OK. don't upload just commit and push

**Comment by Supergoed1** [comment]
I added the source (accidentally on my new account). Yes it is a mess. I made this 8 months ago and have gotten better since then.
